### ISSUE TITLE
Logger Crash

### ISSUE THREAD

**Issue by hhergeth** [WolfRevo/climate.spzb0001_thermostat#2]
The line
`_LOGGER.debug("%s.SetPointTemp = %s", self.heater_entity_id, state_temp.attributes[ATTR_TEMPERATURE])`
was crashing for me because state_temp was None (which is covered in the following ifs)
so I had to change it to:
`        _LOGGER.debug("%s.SetPointTemp = %s", self.heater_entity_id, state_temp.attributes[ATTR_TEMPERATURE] if state_temp != None else None) #SPZB: log for debugging
`

**Comment by WolfRevo** [comment]
I changed it. Have a check so I can close the issue.

Side notice: since there are no promising updates regarding the firmware issues with the EUROTRONIC Zigbee SPZB0001 thermostats I decided to switch to another brand without these issues. So in fact I don't need this integration anymore by myself. As there is no huge effort in the moment to take care of such small requests I will still maintain the repo but if the integration becomes disfunctional due to larger changes in HA I will stop support so if someone likes to takeover the maintance please contact me.

**Comment by hhergeth** [comment]
Thanks for the quick response!
Your change looks good, so feel free to close this issue.

Yeah it is unfortunate how little Eurotronic seems to care about these devices. What other brand did you switch to? I had a quick look a while ago but didn't see many other Zigbee thermostats.

I was actually going to have a feature request (heat to target_temp + epsilon before turning off to avoid frequent and short bursts of heating) , but I will have to implement this myself then :D
If you are interested in having this code in here I can do a pull requrest once I get to it.

**Comment by WolfRevo** [comment]
Actually I would suggest to first test one thermostat from Danfoss (Ally) prior to enhance this custom integration. Why?
They are more expensive but they have some noticable advantages:
1. (especially compared to the SPZB0001): if your Zigbee network is running fine (not colliding with your 2.4GHz WiFi) they won't lose the connection over time or dropping any requests (important: first they need the actual firmware update)
2. they are considerable more quiet in operation
3. they are more efficient so the battery is lasting longer
4. they include an internal PID mechanism which in the first week calibrates which lead to a "strange behaviour" in these days as the valve reacts very slowly to remotely changed setpoints. Nevertheless after the calibration time the PID just really works very efficient in opening the valve exactly to hold the temperature over time (also refer to my [BUG report](https://github.com/zigpy/zha-device-handlers/issues/1005) which after rethinking it is a feature, I am just waiting for a community response to understand their opinion in it)
5. additionally they accept an externally measured temperature to be included in their PID (scripts are available in the HA community) so no need for the custom integration, that's a banger
6. and on top of that it also accepts an externally set boolean to trigger the window open detection, perfect for magnet sensors on windows or doors to trigger that, works like a charm

The firmware update was also quit easy: download the latest version 1.08 from Danfoss, put the binary (deflated) into the corresponding OTA folder and the thermostat will grab it. The only need for me was to delete the thermostat in HA afterwards and to newly connect it so HA gets the new firmware features right (the change of the temperature range for instance which is 5-30°C after the firmware update, but 6-28°C in the first release). Besides that Danfoss also provides a really good [Zigbee integration documentation](https://assets.danfoss.com/documents/176987/AM375549618098en-000101.pdf) for this thermostat.

Last but not least their design is just sleek and modern 😉

**Comment by hhergeth** [comment]
Thanks for the super detailed answer!
I was convinced and ordered a Danfoss Ally thermostat : )

Quick report:
They are indeed more stylish and quiet. Using the external temperature sensor as well as the window open flag worked like a charm. In case anyone reads this at a later point: [this blueprint](https://community.home-assistant.io/t/danfoss-ally-trv-set-external-temperature-with-deconz-integration/296842) works nicely with deconz and can be easily adapted for the window open detection.
Another bonus is that they work very nicely with deconz and performing the firmware update took a while but worked without a problem (in comparison to the Eurotronic thermostats which I wasn't able to update).
