### ISSUE TITLE
ZWAVE?

### ISSUE THREAD

**Issue by RalphM77** [WolfRevo/climate.spzb0001_thermostat#3]
Hey

Do you think this will also work with the ZWAVE Version of the Spirit?

Thanks

R

**Comment by WolfRevo** [comment]
Hey Ralph,

as far as I know the implementation of the firmware between the zigbee and zwave models is quit different. So I can't answer it easily.

If the heating setpoint is changed in the same attribute and if the same HVAC models are supported it could work also with the zwave implementation. You could give it a try with one of your zwave models and report back. The thermostat implementation itself is based on the generic_thermostat from HA and is mostly independent from the used protocols and subsystems (like ZHA, deconz or Zwave).
